file_roots:
  flashcards:
    - /srv/saltstack/apps/
  enigma:
    - /srv/saltstack/apps/
  vids:
    - /srv/saltstack/apps/
  clickbane:
    - /srv/saltstack/apps/
pillar_roots:
  flashcards:
    - /srv/saltstack/pillars
  enigma:
    - /srv/saltstack/pillars
  vids:
    - /srv/saltstack/pillars
  clickbane:
    - /srv/saltstack/pillars
