file_roots:
  grafana:
    - /srv/saltstack/config/
  zabbix:
    - /srv/saltstack/config/
  graylog:
    - /srv/saltstack/config/
  jenkins:
    - /srv/saltstack/config/
  jenkins_node:
    - /srv/saltstack/config/
  mysql:
    - /srv/saltstack/config/
  mariadb:
    - /srv/saltstack/config/
pillar_roots:
  grafana:
    - /srv/saltstack/pillars
  zabbix:
    - /srv/saltstack/pillars
  graylog:
    - /srv/saltstack/pillars
