file_roots:
  tududi:
    - /srv/saltstack/services/
  homepage:
    - /srv/saltstack/services/
  pihole:
    - /srv/saltstack/services/
  myspeed:
    - /srv/saltstack/services/
  navidrome:
    - /srv/saltstack/services/
  booklore:
    - /srv/saltstack/services/
  
pillar_roots:
  tududi:
    - /srv/saltstack/pillars
  pihole:
    - /srv/saltstack/pillars
  homepage:
    - /srv/saltstack/pillars
  myspeed:
    - /srv/saltstack/pillars
  navidrome:
    - /srv/saltstack/pillars
  booklore:
    - /srv/saltstack/pillars
