file_roots:
  tududi:
    - /srv/saltstack/services/
  homepage:
    - /srv/saltstack/services/
  pihole:
    - /srv/saltstack/services/
  myspeed:
    - /srv/saltstack/services/
  navidrome:
    - /srv/saltstack/services/
  booklore:
    - /srv/saltstack/services/
  netalertx:
    - /srv/saltstack/services/
  dockhand:
    - /srv/saltstack/services/
  registry:
    - /srv/saltstack/services/
  jasperserver:
    - /srv/saltstack/services/

pillar_roots:
  tududi:
    - /srv/saltstack/pillars
  pihole:
    - /srv/saltstack/pillars
  homepage:
    - /srv/saltstack/pillars
  myspeed:
    - /srv/saltstack/pillars
  navidrome:
    - /srv/saltstack/pillars
  booklore:
    - /srv/saltstack/pillars
  dockhand:
    - /srv/saltstack/pillars
  jasperserver:
    - /srv/saltstack/pillars
