#!/bin/bash

me=`basename "$0"`
today=$(date "+%Y-%m-%dT%H:%M")

if [[ $EUID -ne 0 ]]; then
  echo "Please run this script with root user"
  exit 1
fi


echo "starting script $me $today"

cd /srv/saltstack/
git pull

echo "Refreshing base"
salt '*' state.highstate \ saltenv=base # -l debug

echo "Refreshing {{ srv }}"
salt '*' state.highstate \ saltenv={{ srv  }} # -l debug

echo "Be polite and say bye..."
