#!/bin/bash

me=`basename "$0"`
today=$(date "+%Y-%m-%dT%H:%M")

echo "starting script $me $today"

cd /srv/saltstack/
git pull

echo "Refreshing base"
salt '*' state.highstate \ saltenv=base # -l debug

echo "Refreshing {{ env }}"
salt '*' state.highstate \ saltenv={{ srv  }} # -l debug

echo "Be polite and say bye..."