version: '3'
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3050:3000
    restart: unless-stopped
    volumes:
      - /opt/grafana/data:/var/lib/grafana
      - /opt/grafana/grafana.ini:/etc/grafana/grafana.ini
      - /opt/grafana/provisioning:/etc/grafana/provisioning

