services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-sandbox
    hostname: jenkins
    domainname: jenkins.greece.local
    mac_address: 62:db:46:95:d1:62
    privileged: true
    user: root
    ports:
      - 8091:8080
      - 50000:50000
    volumes:
      - /opt/jenkins/home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_nw
  agent:
    image: 192.168.1.217:5000/jenkins_java_agent
    container_name: jenkins-sandbox-agent
    hostname: jenkins-agent
    domainname: jenkins-agent.greece.local
    mac_address: e2:26:76:25:9f:8b
    privileged: true
    user: root
    expose:
      - 22
    networks:
      - jenkins_nw
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBLIC_KEY}
  rustagent:
    image: 192.168.1.217:5000/rustmeup
    container_name: jenkins-sandbox-rustagent
    hostname: jenkins-rustagent
    domainname: rustagent.greece.local
    mac_address: 42:ae:1c:3c:5b:82
    privileged: true
    user: root
    expose:
      - 22
    volumes:
      - /opt/jenkins/home:/opt/rust/workspace
    networks:
      - jenkins_nw
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBLIC_KEY}
networks:
  jenkins_nw:
    external: true
