services:
  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    ports:
      - {{ salt['pillar.get']('dockhand_nginx_port') }}:3000
    environment:
      DATABASE_URL: postgres://${PGURL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/dockhand/data:/app/data
    restart: unless-stopped

volumes:
  dockhand_data:
