services:
  homepage:
    image: germannewsmaker/myspeed
    container_name: myspeed
    ports:
      - {{ salt['pillar.get']('myspeed_container_port') }}:5216
    volumes:
      - /opt/myspeed/data:/myspeed/data
    restart: unless-stopped
