---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/docker/

# my-docker:
#   host: 127.0.0.1
#   port: 2375

helios:
  host: 192.168.1.207
  port: 2375

bors:
  host: 192.168.1.217
  port: 2375

tanit:
  host: 102.168.1.23
  port: 2375
