- Network & Monitoring:
    - Pi-Hole:
        href: http://helios.greece.local:88/admin/
        siteMonitor: http://192.168.1.207:88
        icon: pi-hole.png
        description: Network-wide ad blocking & DNS
        server: helios
        container: pihole
        widget:
          type: pihole
          url: http://192.168.1.207:88
          version: 6
          key: {{ salt['pillar.get']('pihole_pass') }}
    - MySpeed:
        href: http://bors.greece.local:{{ salt['pillar.get']('myspeed_nginx_port') }}/
        icon: myspeed.png
        description: MySpeed
        server: bors
        container: myspeed
        widget:
          type: myspeed
          url: http://192.168.1.217:{{ salt['pillar.get']('myspeed_nginx_port') }}
          password: {{ salt['pillar.get']('myspeed_pass') }}
    - Zabbix:
        href: http://helios.greece.local:8080/
        icon: zabbix.png
        description: Monitoring
        widget:
          type: zabbix
          url: http://192.168.1.207:8080
          key: {{ salt['pillar.get']('zabbix_monitoring_api') }}
    - NetAlertX:
        href: http://helios.greece.local:20211/
        icon: netalertx.png
        description: NetAlertX
        server: helios
        container: netalertx
        widget:
          type: netalertx
          url: http://192.168.1.207:20212 # use backend port for widget version 2+
          key: {{ salt['pillar.get']('netalertx_monitoring_api') }}
          version: 2 # optional, default is 1
    - Router:
        href: https://192.168.1.1/login.html
        icon: awwesome.png
        description: Router

- Tools:
    - Graylog:
        href: https://graylog.greece.local:4443
        icon: graylog.png
        description: Centralized log management
        server: helios
        container: graylog-graylog-1
    - Grafana:
        href: http://helios.greece.local:3000/
        icon: grafana.png
        description: Grafs & Stuff
        server: helios # The docker server that was configured
        container: grafana
    - Jenkins:
        href: http://helios.greece.local:8090/
        icon: jenkins.png
        description: My Valet
        server: helios # The docker server that was configured
        container: jenkins-sandbox
    - DockHand:
        href: http://bors.greece.local:{{ salt['pillar.get']('dockhand_nginx_port') }}/
        icon: dockhand.png
        description: DockHand
        server: bors # The docker server that was configured
        container: dockhand
        widget:
          type: dockhand
          url: http://bors.greece.local:{{ salt['pillar.get']('dockhand_nginx_port') }}/api
          environment: local # optional: name or id; aggregates all when omitted
          username: {{ salt['pillar.get']('dockhand_user') }}
          password: {{ salt['pillar.get']('dockhand_password') }}
    - InfluxDB:
        href: http://bors.greece.local:8086/
        icon: influxdb.png
        description: Influx

- Stuff:
    - Booklore:
        href: http://bors.greece.local:{{ salt['pillar.get']('booklore_container_port') }}/dashboard
        icon: booklore.png
        description: Books
        server: bors
        container: booklore
        widget:
          type: booklore
          url: http://bors.greece.local:{{ salt['pillar.get']('booklore_container_port') }}/
          username: {{ salt['pillar.get']('booklore_user') }}
          password: {{ salt['pillar.get']('booklore_password') }}
    - Navidrome:
        href: http://bors.greece.local:4533/
        icon: navidrome.png
        description: Music maestro
        server: bors
        container: navidrome
        widget:
          type: navidrome
          url: http://192.168.1.217:4533
          user: rust
          token: {{ salt['pillar.get']('navidrome_token') }}
          salt: jackandjill
    - Tududi:
        href: http://bors.greece.local:3102/
        icon: tududi.png
        description: todo stuff
        server: bors
        container: tududi
