## Firewall command

### Salt
#public:
#  firewalld.present:
#    - name: public
#    - prune_services: False
#    - default: False
#    - masquerade: False
#    - ports:
#      - 10050-10051/tcp

# sudo ufw allow 8080

ufw allow 8080/tcp:
  cmd.run:
    - unless: "ufw status verbose | grep '8080/tcp'"

## Files 


zabbix_server_configuration:
  file.managed:
    - name: /etc/zabbix/zabbix_server.conf
    - source: salt://zabbix_server/zabbix_server.conf
    - template: jinja
    - create: True