services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    domainname: grafana.greece.local
    mac_address: e2:b8:31:2a:3b:b8
    ports:
      - 3050:3000
    restart: always
    volumes:
      - /opt/grafana/data:/var/lib/grafana
      - /opt/grafana/grafana.ini:/etc/grafana/grafana.ini
      - /opt/grafana/provisioning:/etc/grafana/provisioning
